### ISSUE TITLE
changing /graphql location

### ISSUE THREAD

**Issue by srini85** [JosephWoodward/graphiql-dotnet#6] opened 2017-09-07 01:22 UTC
Looks like this is not quite working as its supposed to. My understanding is that we need to change the js file aswell if we specify an alternate location

in index.html

```
function graphQLFetcher(graphQLParams) {
        // This example expects a GraphQL server at the path /graphql.
        // Change this to point wherever you host your GraphQL server.
        return fetch('/graphql', {
          method: 'post',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
          },
```
Wanted to see if I could fix it but ran into issues when I tried to reference the source as a project reference.

I pulled the source and did a build, when I referenced the project, I couldn't get the graphiql page to load. The /graphql endpoint was just not serving up the static pages.. Not too sure why. The dll in nuget definitely works so wondering if that is a different version to what is in master?

**Comment by josephwoodward** [comment] 2017-09-07 01:27
Hi @srini85,

Thanks for raising this, I'll have to take a look to confirm then get back to you.

**Comment by simonpetty** [comment] 2017-09-25 19:41
@srini85 it seems ok when running the example project. what was your plan with this? i'm not sure how best to templatize the html, since it's just an embedded file

**Comment by srini85** [comment] 2017-09-25 21:18
@simonpetty want to use an alternative location to /graphql. I was thinking of doing it at build time by setting it in the configuration json and then using that as part of the build process. However I couldn't get the project working when I built it myself. So hence wondering if the nuget version is different to the the master src.

**Comment by josephwoodward** [comment] 2017-09-26 05:20
Another option would be to use the .NET Core proxy library to capture requests to a custom endpoint and proxy them to /graphql.

@srini85 Were you working from a fresh clone of master? I've just did a hard reset (`git reset --hard origin/master`) to master, then a `dotnet restore` then ran (using `dotnet run`) the samples project then navigated to http://localhost:5000/graphql/ and can confirm it works.

How are you launching it?

**Comment by josephwoodward** [comment] 2017-09-26 10:02
@srini85 I've just tried launching Graphiql from a custom location (`/hello` instead of the default `/graphql`) and can confirm that it does work. Can you provide a repository of what you're trying to do so I can take a look?

**Comment by srini85** [comment] 2017-09-26 20:47
@JosephWoodward I will see if I get time to push that repository I was working with. Maybe I am missing something, but deffinately did work of a fresh clone of master with no changes. But if you are confirming that it deffinately does work, perhaps I am missing some step or my environment is not quite right. I will continue to dig and let you know the result. 

Just out of curiousity, when you said it worked, are you referring to graphiql loading or loading and making requests to the server? Seeing that the fetch promise is set to `/graphql`, wondering how that gets updated if your controller location is set to something like `/hello` (as per the original issue comment)?

**Comment by josephwoodward** [comment] 2017-09-27 03:32
@srini85 It's done [here](https://github.com/JosephWoodward/graphiql-dotnet/blob/master/src/graphiql/GraphiQlExtensions.cs#L38), allowing you to serve files from a specific location.

**Comment by simonpetty** [comment] 2017-09-27 05:50
The graphiql page loads but the post when submitting a query doesn't work. Another idea is to use an InMemoryFileProvider for the JavaScript currently in the html page, which we can modify with the correct path. Will try to get a version of this going.

**Comment by josephwoodward** [comment] 2017-09-28 08:38
@simonpetty Weird, I'm sure I tried posting a query, I'll take another look and check it out. I think there are a few options we could use to get that working, such as the proxy which I mentioned above.

**Comment by PeterHageus** [comment] 2017-10-23 11:41
> Another option would be to use the .NET Core proxy library to capture requests to a custom endpoint and proxy them to /graphql.

This does not work when hosting under IIS virtual directory. For me a path relative to  graphiql would solve the issue...

**Comment by poulad** [comment] 2018-02-18 23:42
I also am trying to change the routes to `/foo/graphiql` and `/bar/graphql`. The problem is client side requests are always made for `/graphql` path.

https://github.com/JosephWoodward/graphiql-dotnet/blob/979199d78ab4c393617416eb4e7cc3605032c5ec/src/graphiql/assets/index.html#L112

**Comment by josephwoodward** [comment] 2018-02-19 04:43
Yeah, this seems to be the biggest blocker. I'm considering adding a template string to the `index.html` then doing a replace on it, something like:

```javascript
return fetch('{{ graphqlPath }}', { 
```

Seems like the easiest option.

**Comment by poulad** [comment] 2018-02-19 17:00
@JosephWoodward That should work. Do you think we would have a release anytime soon?

**Comment by josephwoodward** [comment] 2018-02-19 17:15
@pouladpld Hopefully either this week or next by the latest.

**Comment by poulad** [comment] 2018-02-19 17:18
Can't wait :smile: I'll try making a PR.

**Comment by FrankyBoy** [comment] 2018-08-07 14:10
Hello. Could we please get this issue addressed? We are facing the same issue, as Graphql is part of a versioned solution (so it runs as my.service.com/1.0/graphql). Actually simply removing the path from here https://github.com/JosephWoodward/graphiql-dotnet/blob/master/src/graphiql/assets/index.html#L112 should do the trick as it then makes a request to the resource itself. That should satisfy all cases, regardless if you are hosting under a completely custom URL or "just" in a subdirectory like we are.

**Comment by josephwoodward** [comment] 2018-08-10 00:41
Have an open PR for this (https://github.com/JosephWoodward/graphiql-dotnet/pull/23) which I'm currently testing an will release in the next few days.

**Comment by josephwoodward** [comment] 2018-08-20 21:04
This has now been released as a beta package, if you would mind giving it a try and reporting back if you find any issues. You can find the beta [here](https://www.nuget.org/packages/graphiql/1.2.0-beta).

I'd like to give a special thanks for @pouladpld for his pull request to get the ball rolling on this.

**Comment by FrankyBoy** [comment] 2018-08-21 08:49
Hi!

We are currently testing this. While this change allows us to explicitly set our path (eg. `"/1.0/GraphQl"`), I would argue this change would work better if [this variable](https://github.com/JosephWoodward/graphiql-dotnet/blob/571732a6f9cadb581ff912ef65f3bd920ebb35c6/src/graphiql/GraphiQlExtensions.cs#L12) is an empty string (so that calls on the interface go to the same URL the interface is hosted on) or at least [this check](https://github.com/JosephWoodward/graphiql-dotnet/blob/571732a6f9cadb581ff912ef65f3bd920ebb35c6/src/graphiql/GraphiQlExtensions.cs#L22) should be removed so we can manually do `app.UseGraphiQl("");` if we want this behaviour.

Cheers

**Comment by FrankyBoy** [comment] 2018-08-21 09:08
Actually, digging deeper, the real problem is that GraphiQL treats the server and JS paths the same. If you have a setup in IIS like this ... 
![image](https://user-images.githubusercontent.com/265792/44392214-f825af80-a531-11e8-892b-a2fbbf786f7e.png)
Then IIS strips the "1.0" out of the path. So from JS side your URL is `/1.0/graphql` while from C# side (i.e. in `GraphiQlConfig` or the `FileServerOptions` built [here](https://github.com/JosephWoodward/graphiql-dotnet/blob/571732a6f9cadb581ff912ef65f3bd920ebb35c6/src/graphiql/GraphiQlExtensions.cs#L42)) the path should just be `/graphql`.

**Comment by josephwoodward** [comment] 2018-08-21 09:40
Thanks for giving the beta try!

> So from JS side your URL is /1.0/graphql while from C# side (i.e. in GraphiQlConfig or the FileServerOptions built here) the path should just be /graphql

I don't have IIS to hand as I use a Mac/Linux, any thoughts how we could resolve this? Not sure how we could get around IIS stripping values from the path, feels like that shouldn't be the responsibility of this library. Thoughts?

**Comment by FrankyBoy** [comment] 2018-08-21 09:46
Yes, I am absolutely with you, it's not your responsibility to know that. Obvious "worst case" solution is allowing setting of JS and C# paths separately, but that really isn't elegant.

**Comment by josephwoodward** [comment] 2018-08-22 14:12
@FrankyBoy Though I'm wondering if there would be any use cases for adding an overload to enable you to configure the JS and C# paths separately. I'm not completely against the idea.

**Comment by FrankyBoy** [comment] 2018-08-22 14:50
Other than my use case (i.e. IIS being weird) I see also this one: Having a separate configuration would make sense if someone wants to host the UI in a different location than the actual graphql endpoint. Like `/docs` for the interface and `/graphql` for the actual graphql endpoint. That would require different paths for the FileServerOptions and the path in the delivered JS as well. You could even target another server entirely (for instance to host a sort of centralized documentation site where you can switch between different services quickly).

Not sure if anyone would ever want to do that, it's just another potential use case I see.

**Comment by FrankyBoy** [comment] 2018-09-06 09:39
Any update here? Should I just push a change that lets us configure server and client path independently or can you look into the topic?

Cheers!

**Comment by josephwoodward** [comment] 2018-10-19 20:04
[1.2.0 has now been published to NuGet](https://www.nuget.org/packages/graphiql/1.2.0), I will now close this PR. If anyone has any issues then please feel free to reopen it.

**Comment by areyes21** [comment] 2019-07-08 21:15
In my solution works normally but when publish in IIS server show this empty string "" 
![imagen](https://user-images.githubusercontent.com/37639639/60843151-18cf1600-a193-11e9-8c3d-c366f541f286.png)

**Comment by areyes21** [comment] 2019-07-08 21:24
In my Solution is fine, Which may be?
![imagen](https://user-images.githubusercontent.com/37639639/60843616-6e57f280-a194-11e9-925d-aaf35f09f1d9.png)

**Comment by josephwoodward** [comment] 2019-07-09 10:24
@areyes21 That's odd. If you perform the query via a raw HTTP Request (as opposed to using GraphiQL), do you get any results? That would isolate the issue to this library.

Also, have you looked in your browser's dev tools? GraphiQL queries your API via an ajax request so it would seem that your API is returning no data?

Is the schema viewer working?

**Comment by areyes21** [comment] 2019-07-09 15:33
The route of **graphqlpath** is /GraphQL But if I change graphqlpath for an empty string it works well.

Line of code 
![imagen](https://user-images.githubusercontent.com/37639639/60901375-128c7880-a22b-11e9-9fc8-e57a9c8ef2b1.png)


![imagen](https://user-images.githubusercontent.com/37639639/60901126-a1e55c00-a22a-11e9-9bc6-de2db575aa67.png)

![imagen](https://user-images.githubusercontent.com/37639639/60902225-81b69c80-a22c-11e9-8b85-b2afb595918e.png)

**Comment by josephwoodward** [comment] 2019-07-09 16:20
Is there any chance you'd be able to create a repo of this issue as I'm struggling to reproduce it?

Alternatively, what does your configuration look like? I see you're running it from localhost in your screenshots? Earlier you mentioned it was only when you published your app to IIS? (or does it also do it if you're running it via IIS locally?)

**Comment by areyes21** [comment] 2019-07-10 15:37
Sorry I do not speak English but I will do my best to explain

**Comment by areyes21** [comment] 2019-07-10 16:09
I could solve it, adding what I show in the screenshots (EN)
Lo pude resolver, agregando lo que le muestro en las capturas de pantalla  (ES)

![imagen](https://user-images.githubusercontent.com/37639639/60984891-ab89c500-a2f9-11e9-98d8-eb8dd6155a1c.png)

![imagen](https://user-images.githubusercontent.com/37639639/60985142-2d79ee00-a2fa-11e9-911e-7f4d2929f0c8.png)

![imagen](https://user-images.githubusercontent.com/37639639/60985370-9eb9a100-a2fa-11e9-8b76-dc7cf0ea5f61.png)

**Comment by areyes21** [comment] 2019-07-10 16:10
Thanks for all the help, Greetings from Nicaragua

**Comment by josephwoodward** [comment] 2020-02-29 19:37
I'm glad you got this sorted in the end, I'm going to mark this issue as closed.

**Closed as completed by josephwoodward** 2020-02-29 19:37 UTC
